#include QMK_KEYBOARD_H
#include "instant_qwerty_reasons.h"
#include "layers.h"
#include "oled.h"
#include "features/caps_word.h"
#include "features/clipboard_shortcuts.h"
#include "features/compact_russian_layout.h"
#include "features/fast_keycode.h"
#include "features/instant_qwerty.h"
#include "features/language_stash.h"
#include "features/language.h"
#include "features/non_qwerty_shortcuts.h"
#include "features/os.h"
#include "features/select_word.h"
#include "features/text_editing.h"


enum custom_keycodes {
    KC_BASE = SAFE_RANGE,   // Cycle through base layouts (Qwerty, Colemak)
    KC_OS,                  // Cycle through operating systems

    KC_LOWER,
    KC_RAISE,

    KC_WSEL,                // Select word

    KC_WPREV,               // Previous word
    KC_WNEXT,               // Next word
    KC_LSTRT,               // Line start
    KC_LEND,                // Line end

    KC_WBSPC,               // Delete from the cursor to the beginning of the word
    KC_WDEL,                // Delete from the cursor to the end of the word

    KC_FUP,                 // Fast up
    KC_FDOWN,               // Fast down
    KC_FSPC,                // Fast space
};


#define MT_LGUI     LGUI_T(KC_LNG1)
#define MT_RGUI     RGUI_T(KC_LNG2)
#define L_NUM       MO(NUMPAD)

#define KC_LDEL     C(S(KC_K))

#define OSM_LSFT    OSM(MOD_LSFT)
#define OSM_RSFT    OSM(MOD_RSFT)


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |  [   |  ]   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | ESC  |  Q   |  W   |  E   |  R   |  T   |                    |  Y   |  U   |  I   |  O   |  P   | BSPC |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | TAB  |  A   |  S   |  D   |  F   |  G   |,------.    ,------.|  H   |  J   |  K   |  L   | ; :  | ' "  |
 * |------+------+------+------+------+------|| MPLY |    |      ||------+------+------+------+------+------|
 * |Shift |  Z   |  X   |  C   |  V   |  B   |`------'    `------'|  N   |  M   | , <  | . >  | / ?  |Shift |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               |Super | LALT | LCTL |/LOWER / SPC  /    \L_NUM \RAISE \| RCTL | RALT |Super |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */
[QWERTY] = LAYOUT( \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                      XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_LBRC,  KC_RBRC, \
KC_ESC,   KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,                         KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,     KC_BSPC, \
KC_TAB,   KC_A,     KC_S,     KC_D,     KC_F,     KC_G,                         KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN,  KC_QUOT, \
OSM_LSFT, KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,     KC_MPLY,  XXXXXXX,  KC_N,     KC_M,     KC_COMM,  KC_DOT,   KC_SLSH,  OSM_RSFT, \
                    MT_LGUI,  KC_LALT,  KC_LCTL,  KC_LOWER, KC_SPC,   L_NUM,    KC_RAISE, KC_RCTL,  KC_RALT,  MT_RGUI \
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  | F10  | F11  | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | ESC  |  Q   |  W   |  F   |  P   |  B   |                    |  J   |  L   |  U   |  Y   |      | BSPC |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | TAB  |  A   |  R   |  S   |  T   |  G   |,------.    ,------.|  M   |  N   |  E   |  I   |  O   |      |
 * |------+------+------+------+------+------|| MPLY |    |      ||------+------+------+------+------+------|
 * |Shift |  Z   |  X   |  C   |  D   |  V   |`------'    `------'|  K   |  H   | , <  | . >  |      |Shift |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               |Super | LALT | LCTL |/LOWER / SPC  /    \L_NUM \RAISE \| RCTL | RALT |Super |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */
[COLEMAK] = LAYOUT( \
KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,                        KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,   KC_F12, \
KC_ESC,   KC_Q,     KC_W,     KC_F,     KC_P,     KC_B,                         KC_J,     KC_L,     KC_U,     KC_Y,     XXXXXXX,  KC_BSPC, \
KC_TAB,   KC_A,     KC_R,     KC_S,     KC_T,     KC_G,                         KC_M,     KC_N,     KC_E,     KC_I,     KC_O,     XXXXXXX, \
OSM_LSFT, KC_Z,     KC_X,     KC_C,     KC_D,     KC_V,     KC_MPLY,  XXXXXXX,  KC_K,     KC_H,     KC_COMM,  KC_DOT,   XXXXXXX,  OSM_RSFT, \
                    MT_LGUI,  KC_LALT,  KC_LCTL,  KC_LOWER, KC_SPC,   L_NUM,    KC_RAISE, KC_RCTL,  KC_RALT,  MT_RGUI \
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  | F10  | F11  | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |  @   |  #   |  $   |  %   |  ^   |                    |  &   |  *   |  (   |  )   | ; :  | BSPC |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |  ~   | = +  |  +   | - _  |  _   |,------.    ,------.| ' "  |  "   |  [   |  ]   |  :   |  |   |
 * |------+------+------+------+------+------||      |    |      ||------+------+------+------+------+------|
 * |      | ` ~  |  ?   |  !   | / ?  | \ |  |`------'    `------'|  {   |  }   |  <   |  >   | , <  |      |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               | LGUI | ___  | ___  |/ ___  /      /    \ ___  \ ___  \| ___  | ___  | RGUI |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */
[LOWER] = LAYOUT( \
KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_F6,                        KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,   KC_F12, \
XXXXXXX,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_CIRC,                      KC_AMPR,  KC_ASTR,  KC_LPRN,  KC_RPRN,  KC_SCLN , KC_BSPC, \
XXXXXXX,  KC_TILD,  KC_EQL,   KC_PLUS,  KC_MINS,  KC_UNDS,                      KC_QUOT,  KC_DQUO,  KC_LBRC,  KC_RBRC,  KC_COLN,  KC_PIPE, \
XXXXXXX,  KC_GRV,   KC_QUES,  KC_EXLM,  KC_SLSH,  KC_BSLS,  XXXXXXX,  XXXXXXX,  KC_LCBR,  KC_RCBR,  KC_LT,    KC_GT,    KC_COMM,  XXXXXXX, \
                    KC_LGUI,  _______,  _______,  _______,  XXXXXXX,  _______,  _______,  _______,  _______,  KC_RGUI \
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    | NUM  |      |      |      |  /   |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |  0   |  1   |  2   |  3   |  *   | BSPC |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | LSFT | LALT | LCTL |      |      |,------.    ,------.|      |  4   |  5   |  6   |  -   |      |
 * |------+------+------+------+------+------||      |    |      ||------+------+------+------+------+------|
 * |      |      |      |      |      |      |`------'    `------'|  .   |  7   |  8   |  9   |  +   | PENT |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               | LGUI | ___  | ___  |/      / ___  /    \ ___  \      \| ___  | ___  | RGUI |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */
[NUMPAD] = LAYOUT( \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                      KC_NUM,   XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_PSLS,  XXXXXXX, \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                      KC_0,     KC_1,     KC_2,     KC_3,     KC_PAST,  KC_BSPC, \
XXXXXXX,  KC_LSFT,  KC_LALT,  KC_LCTL,  XXXXXXX,  XXXXXXX,                      XXXXXXX,  KC_4,     KC_5,     KC_6,     KC_PMNS,  XXXXXXX, \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_PDOT,  KC_7,     KC_8,     KC_9,     KC_PPLS,  KC_PENT, \
                    KC_LGUI,  _______,  _______,  XXXXXXX,  _______,  _______,  XXXXXXX,  _______,  _______,  KC_RGUI \
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      | CAPS |                    |      |      | FUP  | PSCR | INS  | PAUS |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      | ESC  | ` ~  |                    | PGUP |WPREV |  UP  |WNEXT | DEL  | BSPC |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | LSFT | LALT | LCTL | TAB  |      |,------.    ,------.| PGDN | LEFT | DOWN | RGHT | WDEL |WBSPC |
 * |------+------+------+------+------+------|| ___  |    | ___  ||------+------+------+------+------+------|
 * | ___  | UNDO | CUT  | COPY |PASTE |PASTE |`------'    `------'| WSEL |LSTRT |FDOWN | LEND | LDEL | ENT  |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               | LGUI | ___  | ___  |/ ___  / FSPC /    \ ___  \ ___  \| ___  | ___  | RGUI |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */
[RAISE] = LAYOUT( \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_CAPS,                      XXXXXXX,  XXXXXXX,  KC_FUP,   KC_PSCR,  KC_INS,    KC_PAUS, \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_ESC,   KC_GRV,                       KC_PGUP,  KC_WPREV, KC_UP,    KC_WNEXT, KC_DEL,    KC_BSPC, \
XXXXXXX,  KC_LSFT,  KC_LALT,  KC_LCTL,  KC_TAB,   XXXXXXX,                      KC_PGDN,  KC_LEFT,  KC_DOWN,  KC_RGHT,  KC_WDEL,   KC_WBSPC, \
_______,  KC_UNDO,  KC_CUT,   KC_COPY,  KC_PASTE, KC_PASTE, _______,  _______,  KC_WSEL,  KC_LSTRT, KC_FDOWN, KC_LEND,  KC_LDEL,   KC_ENT, \
                    KC_LGUI,  _______,  _______,  _______,  KC_FSPC,  _______,  _______,  _______,  _______,  KC_RGUI \
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      | BASE |                    |  OS  |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |,------.    ,------.|      |      |      |      |      |      |
 * |------+------+------+------+------+------||      |    |      ||------+------+------+------+------+------|
 * | ___  |      |      |      |      |      |`------'    `------'|      |      |      |      |      | ___  |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               | ___  | ___  | ___  |/ ___  / ___  /    \ ___  \ ___  \| ___  | ___  | ___  |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */
[EXTRA] = LAYOUT( \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                      XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX, \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  KC_BASE,                      KC_OS,    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX, \
XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                      XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX, \
_______,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  _______, \
                    _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______,  _______ \
)

};

const struct fast_keycode fast_keycodes[] = {
    {.fast_keycode=KC_FSPC,     .real_keycode=KC_SPC,   .real_count=3},
    {.fast_keycode=KC_FUP,      .real_keycode=KC_UP,    .real_count=5},
    {.fast_keycode=KC_FDOWN,    .real_keycode=KC_DOWN,  .real_count=5},
};

#ifndef countof
#define countof(array)  (sizeof(array)/sizeof(array[0]))
#endif

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (!process_text_navigation_shortcuts(keycode, record, KC_WPREV, KC_WNEXT, KC_LSTRT, KC_LEND))
        return false;
    if (!process_fast_keycodes(keycode, record, fast_keycodes, fast_keycodes+countof(fast_keycodes))) return false;
    if (!process_clipboard_shortcuts(keycode, record)) return false;
    if (!process_editing_history_shortcuts(keycode, record)) return false;
    if (!process_text_deleting_macros(keycode, record, KC_WDEL, KC_WBSPC)) return false;
    if (keycode != KC_LOWER && keycode != KC_RAISE)
        if (!process_caps_word(keycode, record)) return false;
    if (!process_select_word(keycode, record, KC_WSEL)) return false;
    if (!process_compact_russian_layout(keycode, record)) return false;
    if (!process_language(keycode, record)) return false;
    if (!process_os_selector(keycode, record, KC_OS)) return false;

    switch (keycode) {
        case KC_BASE:
            if (record->event.pressed)
                set_single_persistent_default_layer(
                    IS_LAYER_ON_STATE(default_layer_state, QWERTY) ? COLEMAK : QWERTY
                );
            return false;
        case KC_LOWER:
            if (record->event.pressed)
                layer_on(LOWER);
            else
                layer_off(LOWER);
            update_tri_layer(LOWER, RAISE, EXTRA);
            return false;
        case KC_RAISE:
            if (record->event.pressed)
                layer_on(RAISE);
            else
                layer_off(RAISE);
            update_tri_layer(LOWER, RAISE, EXTRA);
            return false;
        case MT_LGUI:
            if (record->tap.count == 1 && record->event.pressed)
                return process_record_user(KC_LNG1, record);
            break;
        case MT_RGUI:
            if (record->tap.count == 1 && record->event.pressed)
                return process_record_user(KC_LNG2, record);
            break;
    }
    return true;
}


void post_process_record_user(uint16_t keycode, keyrecord_t *record) {
    post_process_record_non_qwerty_shortcuts(keycode, record);
}


layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
    case LOWER:
        stash_current_language();
        break;
    default:
        restore_stashed_language();
    }
    return state;
}


void os_set_user(void) {
    clear_language_stash();
    reset_language();
}


void language_set_user(void) {
    clear_language_stash();
    const bool is_secondary = get_language() == SECONDARY_LANGUAGE;
    enable_compact_russian_layout(is_secondary);

    if (get_language() == PRIMARY_LANGUAGE)
        del_instant_qwerty_activation_reasons(NON_ENGLISH_LANGUAGE);
    else
        add_instant_qwerty_activation_reasons(NON_ENGLISH_LANGUAGE);
}


void suspend_power_down_user(void) {
    suspend_power_down_oled();
}


void matrix_init_user (void) {
    if (!host_keyboard_led_state ().num_lock) {
        tap_code(KC_NUM_LOCK);
    }
}
